---
- name: Update all packages on remote host
  hosts: all
  become: true 
  become_method: sudo 
  tasks:
   - name: Update all packages (for Debian/Ubuntu)
     apt:
        update_cache: yes
        upgrade: dist
     when: ansible_os_family == "Debian"
   - name: Update all packages (for RHEL/CentOS/Fedora)
     yum:
       name: '*'
       state: latest
     when: ansible_os_family == "RedHat"

