
- name: Setup web server on remote host
  hosts: webservers
  become: yes
  vars:
   ubuntu_pkg: apache2
   redhat_pkg: httpd
   website_src: ./website
   website_dest: /var/www/html/
  tasks:
   - name: Gather OS facts
     ansible.builtin.setup:
   - name: Set package and service name based on OS
     set_fact:
        webserver_package: "{{ ubuntu_pkg if ansible_facts['os_family'] == 'Debian' else redhat_pkg }}"

        webserver_service: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
   - name: Install web server
     ansible.builtin.package:
       name: "{{ webserver_package }}"
       state: present
   - name: Verify version installed
     command: "{{ webserver_package }} -v"
     register: version_output
     changed_when: false
   - name: Show installed version
     debug:
        msg: "Installed version: {{ version_output.stdout }}"
   - name: Ensure web root directory exists
     ansible.builtin.file:
       path: /var/www/html
       state: directory
       mode: '0755'
   - name: Copy website files
     ansible.builtin.copy:
       src: "{{ website_src }}"
       dest: "{{ website_dest }}"
       mode: '0644'
       owner: root
       group: root
       directory_mode: '0755'
   - name: Start and enable the web server
     ansible.builtin.service:
        name: "{{ webserver_service }}"
        state: started
        enabled: yes
